name: update-stats
concurrency: 'update-stats'

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  update-stats:
    name: repostats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo: ['go-gorm/gorm', 'go-gorm/gen', 'go-gorm/gorm.io', 'go-gorm/playground', 'go-gorm/hints', 'go-gorm/datatypes', 'go-gorm/dbresolver', 'go-gorm/sqlite', 'go-gorm/mysql', 'go-gorm/postgres', 'go-gorm/sqlserver', 'go-gorm/clickhouse']
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@v1.1.0
        with:
          # Define the stats repositories (the repos to fetch stats for and to generate the reports for).
          repository: ${{ matrix.statsRepo }}
          # Set a GitHub API token that can read the stats
          # repository, and that can push to the data
          # repository (which this workflow file lives in),
          # to store data and the report files.
          ghtoken: ${{ secrets.ghrs_github_api_token }}
          # Data branch: Branch to push data to (in the data repo).
          databranch: repo-stats
